In [130]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import LocalOutlierFactor, KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [131]:
off = pd.read_csv('off.csv')
# add the 'label' column to the off dataset
off['label'] = 0
off

0         1       2    3         4         5             6         7  \
0   177.1  0.300000  1771.0  0.0  0.809017  0.587785  3.090170e-01  0.951057   
1   177.1  0.300000  1771.0  0.0  0.309017  0.951057 -8.090170e-01  0.587785   
2   177.1  0.300000  1771.0  0.0 -0.309017  0.951057 -8.090170e-01 -0.587785   
3   177.0  0.447214  1770.0  0.0 -1.618034  0.000000 -1.776357e-14 -1.902113   
4   177.0  0.447214  1770.0  0.0 -1.309017 -0.951057  1.809017e+00 -0.587785   
..    ...       ...     ...  ...       ...       ...           ...       ...   
95  176.7  0.458258  1767.0  0.0 -0.309017  0.951057  1.909830e-01 -1.314328   
96  176.7  0.458258  1767.0  0.0 -0.809017  0.587785  1.309017e+00 -0.224514   
97  176.7  0.458258  1767.0  0.0 -1.000000  0.000000  6.180340e-01  1.175571   
98  176.8  0.400000  1768.0  0.0  0.000000  0.000000 -6.180340e-01  1.902113   
99  176.8  0.400000  1768.0  0.0  0.000000  0.000000 -2.000000e+00  0.000000   

           8         9            10        11  label  
0  -0.309017  0.951057 -8.090170e-01  0.587785      0  
1  -0.809017 -0.587785  3.090170e-01 -0.951057      0  
2   0.809017 -0.587785  3.090170e-01  0.951057      0  
3   0.618034  0.000000 -1.065814e-14 -1.175571      0  
4  -0.190983  0.587785  6.909830e-01  0.951057      0  
..       ...       ...           ...       ...    ...  
95  0.809017 -0.587785  1.309017e+00 -2.126627      0  
96  0.309017  0.951057  1.909830e-01  2.489898      0  
97 -1.000000  0.000000 -1.618034e+00 -1.902113      0  
98  0.000000  0.000000  1.618034e+00  1.175571      0  
99  0.000000  0.000000 -2.000000e+00  0.000000      0  

[100 rows x 13 columns]

In [132]:
on = pd.read_csv('on.csv')
# add the 'label' column to the on dataset
on['label'] = 1
on

0         1       2    3          4          5          6          7  \
0   178.3  3.900000  1783.0  0.0  10.517221   7.641208   4.017221  12.363735   
1   179.0  4.219005  1790.0  0.0   9.680340  16.478231  -8.354102  14.298604   
2   180.4  5.462600  1804.0  0.0   9.472136  27.250124 -11.854102   9.788080   
3   180.8  5.344156  1808.0  0.0  -5.118034  29.964536 -11.736068  -4.445012   
4   180.7  5.423099  1807.0  0.0 -22.562306  20.645729   0.291796 -13.486305   
..    ...       ...     ...  ...        ...        ...        ...        ...   
95  177.8  9.484725  1778.0  0.0  -4.409830 -22.119058 -16.937694  14.747632   
96  178.2  8.829496  1782.0  0.0  12.669697 -18.135586 -18.023799  -7.747209   
97  179.0  9.219544  1790.0  0.0  27.381966  -2.522654   4.270510 -11.927218   
98  179.1  9.267686  1791.0  0.0  24.444272  14.641631  12.972136   1.326840   
99  178.9  9.027181  1789.0  0.0   9.551663  25.037740   2.128677  10.845137   

            8          9         10         11  label  
0   -4.017221  12.363735 -10.517221   7.641208      1  
1  -12.680340  -0.983813  -1.645898  -8.249238      1  
2    0.527864   1.559086  -5.145898  13.935333      1  
3   -2.881966   3.824470  -7.263932 -11.947463      1  
4   -2.437694  -4.873795  13.708204   4.808283      1  
..        ...        ...        ...        ...    ...  
95 -15.590170  38.642558 -37.062306 -13.229035      1  
96 -33.169697 -22.964114  34.523799  -8.731022      1  
97  29.618034 -16.841503 -29.270510  32.058407      1  
98   6.555728  34.323791   4.027864 -42.552785      1  
99 -34.051663  -6.273880  23.371323  35.617875      1  

[100 rows x 13 columns]

In [133]:
on_off = pd.concat([on, off], ignore_index=True)
on_off

0         1       2    3          4          5          6          7  \
0    178.3  3.900000  1783.0  0.0  10.517221   7.641208   4.017221  12.363735   
1    179.0  4.219005  1790.0  0.0   9.680340  16.478231  -8.354102  14.298604   
2    180.4  5.462600  1804.0  0.0   9.472136  27.250124 -11.854102   9.788080   
3    180.8  5.344156  1808.0  0.0  -5.118034  29.964536 -11.736068  -4.445012   
4    180.7  5.423099  1807.0  0.0 -22.562306  20.645729   0.291796 -13.486305   
..     ...       ...     ...  ...        ...        ...        ...        ...   
195  176.7  0.458258  1767.0  0.0  -0.309017   0.951057   0.190983  -1.314328   
196  176.7  0.458258  1767.0  0.0  -0.809017   0.587785   1.309017  -0.224514   
197  176.7  0.458258  1767.0  0.0  -1.000000   0.000000   0.618034   1.175571   
198  176.8  0.400000  1768.0  0.0   0.000000   0.000000  -0.618034   1.902113   
199  176.8  0.400000  1768.0  0.0   0.000000   0.000000  -2.000000   0.000000   

             8          9         10         11  label  
0    -4.017221  12.363735 -10.517221   7.641208      1  
1   -12.680340  -0.983813  -1.645898  -8.249238      1  
2     0.527864   1.559086  -5.145898  13.935333      1  
3    -2.881966   3.824470  -7.263932 -11.947463      1  
4    -2.437694  -4.873795  13.708204   4.808283      1  
..         ...        ...        ...        ...    ...  
195   0.809017  -0.587785   1.309017  -2.126627      0  
196   0.309017   0.951057   0.190983   2.489898      0  
197  -1.000000   0.000000  -1.618034  -1.902113      0  
198   0.000000   0.000000   1.618034   1.175571      0  
199   0.000000   0.000000  -2.000000   0.000000      0  

[200 rows x 13 columns]

In [134]:
# check for NaN values
on_off.isna().sum()

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
label    0
dtype: int64

In [135]:
# Split the dataset into training and testing sets
X = on_off.drop(columns=['label']).to_numpy()
y = on_off['label'].to_numpy() # Ensure the dataset is balanced
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)
# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [136]:
# classification
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train_scaled, y_train)
y_pred = clf.predict(X_test_scaled)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



In [137]:
X_test_scaled[0].reshape(1, -1)

array([[-0.00241992,  0.81713406, -0.00241992,  0.        , -0.201011  ,
        -1.3520278 , -0.95624431,  0.77075602, -0.76627666,  1.88174458,
        -2.35637467, -0.91345929]])

In [138]:
clf.predict(X_test_scaled[0].reshape(1, -1))

array([1])

In [139]:
# anomaly detection with KNN
knn = LocalOutlierFactor(n_neighbors=5, contamination=0.05, novelty=True)
knn.fit(X_train_scaled)
y_pred_knn = knn.predict(X_test_scaled)
y_pred_knn = [1 if x == -1 else 0 for x in y_pred_knn]  # Convert -1 to 1 (anomaly) and 1 to 0 (normal)
sum(y_pred_knn)

3

In [140]:
knn.predict(X_test_scaled[0].reshape(1, -1))

array([1])

In [141]:
# save all the models with pickle
import pickle
with open('knn_model.pkl', 'wb') as f:
    pickle.dump(knn, f)
with open('clf_model.pkl', 'wb') as f:
    pickle.dump(clf, f)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)